cleanup

diff --git a/automarker/auto b/automarker/auto
--- a/automarker/auto
+++ b/automarker/auto
@@ -3,7 +3,7 @@
 executable="./myinterpreter"
 
 totalpassed=0
-for i in 1 2 3 4 5
+for i in 1 2 3 4 5 6 7 8 9 10
 do
 	echo 
 	echo "*****************"
@@ -11,26 +11,34 @@ do
 	echo "*****************"	
 	prog="pr$i.cql"
 	passed=0
-	echo 
-	echo "  ******************************"
-	echo "  *          test $i           *"
-	echo "  ******************************"
 	
-	testdir="pr"
-	testdir+=$i
-	testdir+="/"
-	out="youroutput.csv"
+	for j in 1 2 3 4 5
+	do 
+		echo 
+		echo "  ******************************"
+		echo "  *          test $j           *"
+		echo "  ******************************"
+	
 
-	cp $executable $testdir
-	cp $prog $testdir 
-	cd $testdir 
-	#timeout 10s 
-	$executable $prog > $out 2>/dev/null
+		testdir="./pr"
+		testdir+=$i
+		testdir+="/"
+		testdir+="test"
+		testdir+=$j
+		#testdir+="/"
+		out="youroutput.csv"
 
-	if [ "$?" = 124 ]; then
-		echo -e "  TEST FAILED -- TIMEOUT"
-	else
-		outofficial="out.csv" 
+		cp $executable $testdir
+		cp $prog $testdir 
+		cd $testdir 
+	
+	    #timeout 10s 
+	    $executable $prog > $out 2>/dev/null
+
+		if [ "$?" = 124 ]; then
+			echo -e "  TEST FAILED -- TIMEOUT"
+		else
+			outofficial="out.csv" 
 
 		diff -wB $out $outofficial > /dev/null
 		if [ "$?" = 0 ]; then
@@ -49,12 +57,13 @@ do
 			echo
 			fi
 		fi
+		rm $executable 
+		rm $prog
+		rm $out
+		cd ../..
+	done 
 	echo 
 	echo "$passed tests passed for pr$i"
 	totalpassed=$((totalpassed+passed))
-	rm $executable 
-	rm $prog
-	rm $out
-	cd ..
 done
 echo "$totalpassed tests passed in total"
