Travis setup

diff --git a/autotester/auto b/autotester/auto
--- a/autotester/auto
+++ b/autotester/auto
@@ -1,25 +1,16 @@
 #!/bin/bash
 
-executable="./myinterpreter"
+executable="./smpl"
 
 totalpassed=0
+totalfailed=0
 for i in 1 2 3 4 5 6 7 8 9 10
 do
-	echo 
-	echo "*****************"
-	echo "*     pr $i     *"
-	echo "*****************"	
 	prog="pr$i.cql"
 	passed=0
 	
 	for j in 1 2 3 4 5
 	do 
-		echo 
-		echo "  ******************************"
-		echo "  *          test $j           *"
-		echo "  ******************************"
-	
-
 		testdir="./pr"
 		testdir+=$i
 		testdir+="/"
@@ -43,18 +34,10 @@ do
 		diff -wB $out $outofficial > /dev/null
 		if [ "$?" = 0 ]; then
 			passed=$((passed+1))
-			echo -e "  TEST PASSED" 
 		else
-			echo -e "  TEST FAILED" 
+			totalfailed=$((totalfailed+1))
+			echo -e "[FAILED] pr$i test $j" 
 			echo 
-			echo "  Your output:"
-			echo "  ------------"
-			cat $out | sed "s/^/  /"
-			echo
-			echo "  Correct output:"
-			echo "  ---------------"
-			cat $outofficial | sed "s/^/  /"
-			echo
 			fi
 		fi
 		rm $executable 
@@ -62,8 +45,10 @@ do
 		rm $out
 		cd ../..
 	done 
-	echo 
-	echo "$passed tests passed for pr$i"
 	totalpassed=$((totalpassed+passed))
 done
-echo "$totalpassed tests passed in total"
+echo
+echo "$totalpassed tests passed in total out of $((totalpassed+totalfailed))"
+if [ "$totalfailed" != 0 ]; then
+	exit 1
+fi
